[project]
name = "language_tool_python"
version = "2.9.1"
requires-python = ">=3.9"
description = "Checks grammar using LanguageTool."
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
authors = [
    { name = "Jack Morris", email = "jxmorris12@gmail.com" }
]
urls = { Repository = "https://github.com/jxmorris12/language_tool_python.git" }

dependencies = [
    "requests",
    "tqdm",
    "psutil",
    "toml"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-xdist",
    "pytest-cov",
    "pytest-runner"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
