[project]
name = "language_tool_python"
version = "2.8.2"
description = "Checks grammar using LanguageTool."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Jack Morris", email = "jxmorris12@gmail.com" }
]
urls = { Homepage = "https://github.com/jxmorris12/language_tool_python" }

dependencies = [
    "pip",
    "requests",
    "tqdm",
    "wheel"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-xdist",
    "pytest-cov",
    "pytest-runner"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
